wandb_key: c8402d246f6c85ba56487bb7f4d15b5e3b45e781 #WANDB_KEY
metadata_dir: preprocessing
clip_download_dir: CLIP_CHECKPOINT_PATH

dataroot: 'preprocessing' #csv path

synth_train_data_dir: '../generation/output_synthetic_class_wise_135_shot_bg/scabies/sd2.1/gs2.0_nis50/shot16_seed6_template1_lr0.0001_ep300/train' #GLOBAL_PATH_TO_SYNTH_DATA_DIR

real_train_data_dir:
    scabies: 'preprocessing' #PATH_TO_REAL_TRAIN_DATA_DIR

real_test_data_dir:
    scabies: 'preprocessing' #PATH_TO_REAL_TEST_DATA_DIR

real_train_fewshot_data_dir: 
    scabies: '../../../../data/rare_disease/scabies_with_bg_jpg/' #PATH_TO_FEWSHOT_DATA_DIR




